# Title of your site
title: Courtney Graham

# Description of your site
description: My personal website to showcase my projects and development as a full-stack engineer!

# Specify the theme
theme: pages-themes/minimal

# Other configurations (if any)
# Include any additional configurations below
